base_model: roberta-base-nli-stsb-mean-tokens
base_model_dir: models/base
batch_size: 2
train_dir: datasets/train
train_flat_file: train_flat.csv
eval_dir: datasets/eval
dev_file: semeval2007.csv
test_files: [semeval2013.csv, semeval2015.csv, senseval2.csv, senseval3.csv]