base_model: nli-roberta-large
crossencoder_base_model: microsoft/deberta-base
base_model_dir: models/base
batch_size: 32
train_dir: datasets/train
train_flat_file: train_gloss.csv
train_hyp_file: train_hyp.csv
train_combined_file: train_combined.csv
train_triplet_file: train_triplet.csv
eval_dir: datasets/eval
dev_file: semeval2007.csv
warmup_ratio: 0.1
test_files: [all.csv, semeval2007.csv, semeval2013.csv, semeval2015.csv, senseval2.csv, senseval3.csv]
saved_model_dir: model_save
num_epochs: 2
eval_steps: 10000
loss_type: TripletLoss
results_dir: results
use_hypernym: False
train_raw_dir: datasets/train/raw
train_raw_files: [semcor_train_sent_cls_ws.csv, glosses_main_train_sent_cls_ws.csv, examples_train_sent_cls_ws.csv]
oversample_ratio: 3
transfer_learn: True
eval_base: Hypernym_plus_Triplet
checkpoint_path: Hypernym_plus_Triplet
transfer_learn_base: Hypernym
eval_strategy: Simple
keys_file: datasets/semcor_keys.txt